model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "/home/kp66/khushbu/minigpt4Med/ckpts/Llama-2-7b-chat-hf/"
  ckpt: "/home/kp66/khushbu/minigpt4Med/ckpts/checkpoint_stage3.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  mimic_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  openi_cap:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  slake_grounded_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  pmc_vqa:    
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
  
  slake_vqa:    
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  vqa_rad:    
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"


  pmc_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  rocorad_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  rocononrad_caption:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 100
  num_workers: 4
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "/home/kp66/khushbu/minigpt4Med/save_ckpt_new/"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
 
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune_trainable_eva_vit